name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        node: ['12']

    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: ci/deploy.sh 2>&1
        if: success() && github.ref == 'refs/heads/master'
        env:
          AWS_CREDENTIALS: ${{secrets.AWS_CREDENTIALS}}
          GOOGLE_SHEETS_CONFIG: ${{secrets.GOOGLE_SHEETS_CONFIG}}
